[workspace]
members = [
    "03_grammer/concepts",
    "03_grammer/scrape_url",
    "03_grammer/scrape_url_args",
    "03_grammer/scrape_url_with_error_handing",
    "04_httpie",
    "05_thumbor",
    "06_queryer"
, "07_ownership", "08_borrow", "09_multi_owner", "10_lifetime"]
