[package]
name = "ownership"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ownership1"
path = "src/ownership1.rs"

[[bin]]
name = "ownership_error"
path = "src/ownership_error.rs"

[[bin]]
name = "check_copy"
path = "src/check_copy.rs"

[dependencies]
